class TypesOfDeviceModel {
  final replacementDict = {
    'Home Gateway Unificado': 'HGU',
    'HGU HPNA': 'HGU',
    'Set Top Box IPTV': 'IPTV',
    'MitraStar GPT-2731GN2A4P-N2': 'HGU',
    'HGU ECONET ETH Askey': 'HGU',
    'MitraStar GPT-2741GNAC-N2-SV': 'HGU',
    'ARRIS VIP4342W': 'IPTV',
    'HGU Askey sem servi?o SIP': 'HGU',
    'ARRIS VIP4342': 'IPTV',
    'Askey RTF3507VW-N2': 'HGU',
    'ARRIS VIP4242H': 'IPTV',
    'ZAPPER IPTV ETH UHD BLUCASTLE HP4500': 'IPTV',
    'HUMAX PTT100': 'IPTV',
    'MitraStar GPT-2741GNAC-N1': 'HGU',
    'MitraStar GPT-2731GN2A4P': 'HGU',
    'Askey RTF3505VW-N1': 'HGU',
    'HGU_Mitrastar': 'HGU',
    'HGU MitraStar sem voz': 'HGU',
    'Repetidor Smart Wifi': 'SIP',
    'MitraStar GPT-2741GNAC-N2': 'HGU',
    'Set Top Box DVR IPTV': 'IPTV',
    'Set Top Box Zapper': 'IPTV',
    'RTF8115VW-SVAskey': 'HGU',
    'Askey RTF8117VW': 'HGU',
    'Askey RTF3507VW-N1': 'HGU',
    '"Mitrastar_GPT-2742GX4X5v6	"': 'HGU',
    'MitraStar GPT-2541GNAC-N1': 'HGU',
    'Modem - SIP Plus': 'SIP',
    'ATA 2 PORTAS': 'SIP',
    'ATA 4 Portas': 'SIP',
    'HUMAX PTT100W': 'IPTV',
    'HGU ASKEY ECONET RTF8115VW': 'HGU',
    'HGU ASKEY ECONET RTF8115VW-SV SEM VOIP': 'HGU',
    'HGU MITRA ECO GPT-2741GNAC-N2-SV S/VOIP': 'HGU',
    'HOME GATEWAY UNIT - HGU Askey VIVO 1 N2': 'HGU',
    'SET TOP BOX IPTV LOW COST PACE': 'IPTV',
    'HGU MITRA ECO GPT-2741GNAC-N1-SV S/VOIP': 'HGU',
    'HOME GATEWAY UNIT - HGU HPNA ASKEY': 'HGU',
    'ZAPPER IPTV ARRIS PROTHEUS': 'IPTV',
    'HOME GATEWAY UNIT - HGU HPNA MITRASTAR': 'HGU',
    'HGU MITRA ECONET': 'HGU',
    'HOME GATEWAY UNIT - HGU Mitra VIVO 1 N2': 'HGU',
    'ZAPPER IPTV ARRIS PROTHEUS ETH VIP4342': 'IPTV',
    'Askey RTF3505VW-N2': 'HGU',
    'HGU MITRA ECONET GPT-2741GNAC': 'HGU',
    'HGU HPNA ASKEY ECONET RTF8117VW': 'HGU',
    'HGU Wi-Fi 6 Mitrastar GPT2742': 'HGU',
    'HGU Wi-Fi 6 Askey RTF8225VW': 'HGU',
    'HGU HPNA ASKEY - FW VIVO 2': 'HGU',
    'ZAPPER IPTV HUMAX PROTHEUS ETH PTT-100': 'IPTV',
    'ZAPPER IPTV HUMAX PROTHEUS WIFI PTT-100W': 'IPTV',
    'ZAPPER IPTV ARRIS PROTHEUS WIFI VIP4342W': 'IPTV',
    'SET TOP BOX HD PVR - IPTV CISCO': 'IPTV',
    'HGU ECONET ETH Mitra': 'HGU',
    'MitraStar GPT-2541GNAC-N2': 'HGU',
    'Set Top Box WIFI IPTV': 'IPTV',
    'HGU C/ HPNA': 'HGU',
    'IPTV LC PR': 'IPTV',
    'HGU ? SV': 'HGU',
    'IPTV LC ETH': 'IPTV',
    'HGU Wi-Fi 6': 'HGU',
    'IPTV LC WIFI': 'IPTV',
    'HGU – SV': 'HGU',
  };
}
